#### Numpy

In [3]:
import numpy as np

In [7]:

a = np.array([1, 2, 3, 4, 5])           # from list
print("this is a:", a)
b = np.zeros((3, 4))                    # 3x4 zeros
print("this is b:", b)
c = np.ones((2, 3))                     # 2x3 ones
print("this is c:", c)
d = np.full((2, 2), 7)                  # filled with 7
print("this is d:", d)
e = np.arange(0, 10, 2)                 # [0 2 4 6 8]
print("this is e:", e)
f = np.linspace(0, 1, 5)                # 5 evenly spaced values 0→1
print("this is f:", f)

print("Shape of a:", a.shape)
print("Data type of b:", b.dtype)
print("Shape of f:", f.shape)

this is a: [1 2 3 4 5]
this is b: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
this is c: [[1. 1. 1.]
 [1. 1. 1.]]
this is d: [[7 7]
 [7 7]]
this is e: [0 2 4 6 8]
this is f: [0.   0.25 0.5  0.75 1.  ]
Shape of a: (5,)
Data type of b: float64
Shape of f: (5,)


In [8]:
X = np.random.rand(100, 10)   # 100 samples, 10 features
print(X.shape)     # (100, 10) -> n_samples, n_features
print(X.ndim)      # 2
print(X.size)      # 1000
print(X.dtype)     # float64
print(X.nbytes)    # memory footprint

(100, 10)
2
1000
float64
8000


In [10]:
img = np.random.rand(28, 28)
flat = img.reshape(784)        # flatten for ML model
print("Shape of flat:", flat.shape)   # (784,)
back = flat.reshape(28, 28)    # restore
print("Shape of back:", back.shape)   # (28, 28)
assert np.allclose(img, back)

# -1 means "auto-compute this dimension"
m = np.arange(12).reshape(3, -1)   # (3, 4)
print("Shape of m:", m.shape)   # (3, 4)

Shape of flat: (784,)
Shape of back: (28, 28)
Shape of m: (3, 4)


In [13]:
data = np.arange(20).reshape(4, 5)
print("data:", data)
print("data[1, 2]:", data[1, 2])       # row 1, col 2 -> 7
print("data[0]:", data[0])          # first row
print("data[:, 1:3]:", data[:, 1:3])     # all rows, cols 1-2
print("data[::2]:", data[::2])        # every other row
print("data[::-1]:", data[::-1])       # reverse rows

data: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
data[1, 2]: 7
data[0]: [0 1 2 3 4]
data[:, 1:3]: [[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]
data[::2]: [[ 0  1  2  3  4]
 [10 11 12 13 14]]
data[::-1]: [[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [15]:
a = np.arange(10)
v = a[2:5]              # VIEW: shares memory
v[0] = 99
print("a:", a)                # [0 1 99 3 4 ...] -> original changed!

c = a.copy()            # COPY: independent
c[0] = -1
print("a[0]:", a[0])             # still 0

a: [ 0  1 99  3  4  5  6  7  8  9]
a[0]: 0


In [17]:
weights_kg = np.array([70.3, 65.1, 80.0, 55.7])
weights_lb = weights_kg * 2.20462
print("Weights in pounds:", weights_lb.round(2))

Weights in pounds: [154.98 143.52 176.37 122.8 ]


In [19]:
temps = np.array([22.1, 19.8, 25.3, 30.2, 28.7])
print("Mean:", temps.mean())
print("Standard deviation:", temps.std())
print("Minimum:", temps.min())
print("Maximum:", temps.max())
print("Median:", np.median(temps))          # robust to outliers
print("90th percentile:", np.percentile(temps, 90))  # 90th percentile
print("Index of hottest day:", np.argmax(temps))          # index of hottest day

Mean: 25.220000000000002
Standard deviation: 3.8994358566336227
Minimum: 19.8
Maximum: 30.2
Median: 25.3
90th percentile: 29.599999999999998
Index of hottest day: 3


In [20]:
X = np.random.rand(5, 3)
col_mean = X.mean(axis=0)   # mean of each feature -> shape (3,)
row_mean = X.mean(axis=1)   # mean per sample      -> shape (5,)

# Min-max scaling per column
X_scaled = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
print("X_scaled:", X_scaled)

X_scaled: [[0.52801495 0.85156125 0.47957538]
 [0.31287154 1.         0.99364441]
 [1.         0.67507875 1.        ]
 [0.03414394 0.85607629 0.23345712]
 [0.         0.         0.        ]]


In [22]:
W = np.ones((4, 3))
print("W:", W)
bias = np.array([0.1, 0.2, 0.3])
print("W + bias:", W + bias)   # bias added to each row automatically

# Subtract column means from all rows (centering data)
X = np.random.rand(100, 5)
X_centered = X - X.mean(axis=0)

print("X_centered:", X_centered)



W: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
W + bias: [[1.1 1.2 1.3]
 [1.1 1.2 1.3]
 [1.1 1.2 1.3]
 [1.1 1.2 1.3]]
X_centered: [[-0.47574899 -0.43149493 -0.29445218 -0.2555988  -0.23317193]
 [-0.13792552 -0.0998504  -0.38768896 -0.29314072 -0.10738036]
 [-0.16712803  0.02979248 -0.05927577 -0.05799572  0.19922207]
 [ 0.2204712  -0.39820314  0.20796377  0.47431428  0.00383655]
 [-0.01032296 -0.41615608 -0.23302963 -0.12553489 -0.23711531]
 [ 0.30195492  0.07058579 -0.09556029  0.30476143  0.42019204]
 [ 0.45146413 -0.04852569 -0.4981263  -0.28177343  0.27778509]
 [-0.06954632 -0.44801019  0.1765146  -0.47995662  0.39969595]
 [-0.28712382 -0.14123207  0.34460981  0.19867058  0.37028105]
 [-0.37218036 -0.32085045 -0.12842906 -0.34272537  0.34304152]
 [-0.409614    0.38842381  0.15019897  0.30697418  0.4813777 ]
 [ 0.19949071  0.07851701  0.26360393  0.11591193  0.09177435]
 [-0.09353922 -0.31592604  0.42582163  0.22796374  0.49814449]
 [-0.49896667 -0.35689621 -0.24552731 -0.10408

In [23]:
X = np.random.rand(100, 3)     # features

w = np.random.rand(3)          # learned weights

y_pred = X @ w                 # dot product -> shape (100,)

A = np.random.rand(3, 4)
B = np.random.rand(4, 5)
C = A @ B                      # matrix multiply -> (3, 5)
print("C:", C)

C: [[0.6893613  0.32647183 0.6604572  0.35564062 0.54224106]
 [0.90629784 1.03909285 0.72909122 0.8006217  0.79464052]
 [1.48434561 1.29276497 1.21504344 0.90309446 1.19043189]]


In [27]:
ages = np.array([25, 35, 42, 19, 50, 31])
income = np.array([30, 55, 70, 20, 90, 48])

mask = ages > 30
print("Mask for ages > 30:", mask)
print("Incomes of people over 30:", income[mask])
print("Incomes of people over 30 and with income < 60:", income[(ages > 30) & (income < 60)])

Mask for ages > 30: [False  True  True False  True  True]
Incomes of people over 30: [55 70 90 48]
Incomes of people over 30 and with income < 60: [55 48]


In [ ]:
scores = np.array([45, 78, 92, 60, 88])
print("Scores:", scores)
passed = np.where(scores >= 60, 1, 0)     # [0 1 1 1 1]
print("Passed:", passed)
''' how does where condition works: np.where(condition, value_if_true, value_if_false) '''

# Clip outliers
clean = np.clip(scores, 50, 85)
print("Cleaned scores:", clean)
''' how does clip function works: np.clip(array, min_value, max_value)
 - values below min_value are set to min_value and values above max_value are set to max_value '''

Scores: [45 78 92 60 88]
Passed: [0 1 1 1 1]
Cleaned scores: [50 78 85 60 85]


In [ ]:
X = np.arange(20).reshape(10, 2)
idx = np.random.permutation(10)
''' how does permutation works: '''
train_idx, test_idx = idx[:7], idx[7:]

X_train, X_test = X[train_idx], X[test_idx]


In [31]:
probs = np.array([0.1, 0.7, 0.05, 0.9, 0.3])
top2 = np.argsort(probs)[-2:][::-1]   # indices of top 2, highest first
print(top2)                            # [3 1]
print(np.sort(probs))                  # sorted values

[3 1]
[0.05 0.1  0.3  0.7  0.9 ]


In [32]:
data = np.array([[1.0, np.nan], [3.0, 5.0], [np.nan, 7.0]])
col_means = np.nanmean(data, axis=0)
for j in range(data.shape[1]):
    data[np.isnan(data[:, j]), j] = col_means[j]
print(data)

[[1. 6.]
 [3. 5.]
 [2. 7.]]


In [33]:
X = np.c_[np.ones(100), np.random.rand(100)]   # add intercept column
y_true_w = np.array([3.0, 5.0])
y = X @ y_true_w + np.random.randn(100) * 0.1

w_hat = np.linalg.inv(X.T @ X) @ X.T @ y       # recovered ≈ [3, 5]
print(w_hat.round(2))

[3.02 4.99]


In [34]:
X = np.random.randn(200, 2)
X[:, 1] = X[:, 0] * 0.8 + X[:, 1] * 0.2   # correlated features
cov = np.cov(X.T)
vals, vecs = np.linalg.eigh(cov)
principal_axis = vecs[:, np.argmax(vals)]  # direction of max variance
print(principal_axis)

[-0.7862372  -0.61792481]


In [35]:
points = np.random.rand(1000, 2)   # dataset
query = np.array([0.5, 0.5])

dist = np.sqrt(((points - query)**2).sum(axis=1))  # Euclidean to all
nearest = np.argmin(dist)
k_nearest = np.argsort(dist)[:5]                   # 5 nearest neighbors

In [36]:
rng = np.random.default_rng(seed=42)
normal_data = rng.normal(loc=100, scale=15, size=1000)  # ~N(100,15)
sample = rng.choice(['cat', 'dog', 'bird'], size=5, p=[0.5, 0.3, 0.2])
shuffle = rng.permutation(np.arange(10))

In [37]:
rng = np.random.default_rng(0)
n = 500
ad_spend = rng.uniform(0, 100, n)
sales = 20 + 1.5 * ad_spend + rng.normal(0, 8, n)   # linear relation + noise
print(np.corrcoef(ad_spend, sales)[0, 1].round(3))  # ≈ 0.95

0.985


In [38]:
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('salary', 'f8')])
emps = np.array([('Ana', 30, 55000), ('Bob', 45, 80000)], dtype=dt)
print(emps[emps['age'] > 35]['name'])   # ['Bob']

['Bob']


In [39]:
x = np.random.rand(1_000_000)

# Slow: sum of squares via loop
total = 0
for v in x: total += v**2

# Fast: fully vectorized
print((x**2).sum())        # or np.dot(x, x)

333098.8058944683


In [40]:
X = np.random.rand(5, 4) * 10
cv = np.apply_along_axis(lambda r: r.std() / r.mean(), 1, X)
print(cv)

[0.63348087 0.2338431  0.44065327 0.23280283 0.31619405]


In [41]:
rng = np.random.default_rng(1)
heights = rng.normal(170, 10, 10_000)
counts, edges = np.histogram(heights, bins=20)
digitized = np.digitize(heights, bins=[160, 170, 180])  # bucket labels
print(counts[:5])

[  5   8  39  73 166]


In [42]:
from numpy.lib.stride_tricks import sliding_window_view
prices = np.arange(10, dtype=float)
windows = sliding_window_view(prices, 3)     # overlapping chunks of 3
rolling_mean = windows.mean(axis=1)          # moving average
print(rolling_mean)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [43]:
arr = np.memmap('big.dat', dtype='float32', mode='w+', shape=(10000, 1000))
arr[:5] = 1.0
del arr
arr = np.memmap('big.dat', dtype='float32', mode='r', shape=(10000, 1000))
print(arr[0, :3])   # reads only what you touch

[1. 1. 1.]


In [44]:
t = np.linspace(0, 1, 500)
signal = np.sin(2*np.pi*5*t) + 0.5*np.sin(2*np.pi*20*t)
freqs = np.fft.rfftfreq(len(t), d=t[1]-t[0])
spectrum = np.abs(np.fft.rfft(signal))
print(freqs[np.argmax(spectrum[1:]) + 1])   # dominant freq ≈ 5 Hz

4.99


In [45]:
logits = np.random.randn(4, 3)               # 4 samples, 3 classes
exp = np.exp(logits - logits.max(axis=1, keepdims=True))  # stable
probs = exp / exp.sum(axis=1, keepdims=True)
print(probs.sum(axis=1))                     # each row = 1.0

[1. 1. 1. 1.]


In [46]:
labels = np.array([2, 0, 1, 2])
onehot = np.eye(3)[labels]
print(onehot)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
rng = np.random.default_rng(7)
data = np.vstack([
    rng.normal([2, 2], 0.6, (150, 2)),
    rng.normal([8, 8], 0.6, (150, 2)),
    rng.normal([8, 2], 0.6, (150, 2)),
])

centroids = data[rng.choice(len(data), 3, replace=False)]
for _ in range(10):
    # assign each point to nearest centroid
    d = ((data[:, None, :] - centroids)**2).sum(-1)   # (n, k) distances
    labels = d.argmin(axis=1)
    # recompute centroids
    centroids = np.array([data[labels == k].mean(axis=0) for k in range(3)])

print(centroids.round(1))   # ≈ [[2,2],[8,2],[8,8]]

[[8.  2. ]
 [8.  7.8]
 [1.9 1.9]]
