### Recursion Practice


In [5]:
def countdown(n):
    if n==0:
         return 0
    print(n)
    return countdown(n-1)

countdown(5)

5
4
3
2
1


0

In [6]:
def countup(number):
    if number < 1:
        return []
    count_list = countup(number - 1)
    count_list.append(number)
    return count_list

print(countup(5))

[1, 2, 3, 4, 5]


In [7]:
def range_of_numbers(start_num, end_num):
    
    if start_num == end_num:
        return [start_num]
    if start_num > end_num:
        return 'invlaid numbers try again' 

    list_numbers = range_of_numbers(start_num ,end_num - 1)
    list_numbers.append(end_num)
    return list_numbers

print(range_of_numbers(1,9))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
def change_string(string):
    if string == "":
        return ""
    return change_string(string[1:]) + string[0]

print(change_string("Anand"))

dnanA


### Python libraries 

In [3]:
import numpy as np
import matplotlib as mp
import seaborn as sn
import pandas as pd


In [5]:
print('hello python libraries')

hello python libraries


In [11]:
a = 29
b = 49

print('addition of the numbers is: ',a+b)
print('substraction of the numbers is: ',a-b)
print('multiplication of the numbers is: ',a*b)
print('division of the numbers is: ',a/b)

addition of the numbers is:  78
substraction of the numbers is:  -20
multiplication of the numbers is:  1421
division of the numbers is:  0.5918367346938775


In [22]:
n=int(input('Enter number: '))
def count_of(n):
    for i in range (1,n):
        yield i
a = count_of(n)
print(next(a))
print(next(a))
    

Enter number:  5


1
2


### Numpy libraries


In [2]:
import numpy as np

In [5]:
a=np.array([24,32,32,2,24,42])
b=np.array([3,44,2,1,5,31])

print(a + b)
print(a + 2)
print(b + 5)

[27 76 34  3 29 73]
[26 34 34  4 26 44]
[ 8 49  7  6 10 36]


In [7]:
arr = np.array([25,36,10])

print(arr[0]*arr[0])
print(np.sqrt(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

625
[5.         6.         3.16227766]
23.666666666666668
71
36
10


In [19]:
arr = np.arange(1,15)


print("array is: ",arr)
print("shape of the array is: ",arr.shape)
print("size of the array is: ",arr.size)


print("reshape the array into 2 row 7 col: ",arr.reshape(2,7))


array is:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shape of the array is:  (14,)
size of the array is:  14
reshape the array into 2 row 7 col:  [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
arr = np.array([[10,30,20,40],[50,60,70,80]])

arr.shape
arr.reshape(-1)



array([10, 30, 20, 40, 50, 60, 70, 80])

In [24]:
a=np.array([12,45,33])
b=np.array([34,5,33])

print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[12 45 33]
 [34  5 33]]
[12 45 33 34  5 33]


In [28]:
print(np.random.rand(3))
print(np.random.randint(1,10,5))
print(np.random.rand(3,3))


[0.52964999 0.00266342 0.69504444]
[8 5 8 6 1]
[[0.70589424 0.94812443 0.49995971]
 [0.06325212 0.21352174 0.99834058]
 [0.92901194 0.98823344 0.12351498]]


In [30]:
arr = np.array([2,3,55,33])

view = arr.view()
copy = arr.copy()

print(arr)
print(view)
print(copy)


[ 2  3 55 33]
[ 2  3 55 33]
[ 2  3 55 33]


In [32]:
arr[0]=199

print(arr)
print(view)
print(copy)

[199   3  55  33]
[199   3  55  33]
[ 2  3 55 33]


In [ ]:
arr = np.array([1,2,4,5,3])


### Pandas libraries


In [6]:
import pandas as pd

In [16]:
df=pd.read_excel(r'C:\Users\Swami-Anand\Downloads\MessyData _Text Function.xlsx')
df

,last 4 employee id,Employee prefix,Mid Employee_Id,Replace_emp,Employee_ID,clean_lower_name,clean_upper_name,clean_proper_name,Count_clean_name,Create Full_Name_Department,...,Messy_Location,Department,clean_salary_label,Salary_As_numeric,Salary_As_Text,Phone,Clean_Location_Chain,Location_Chain,Clean_Record,final_emp_label
0,1001,EMP,1001,EMP-1001,EMP-1001,priya sharma,PRIYA SHARMA,Priya Sharma,12,Priya Sharma Operations,...,Aurangabad-Maharashtra,Operations,Salary: 45000,45000,45000,+91-7599310825,Pune-Mumbai-Mumbai,Pune-Pune-Mumbai,"EMP-1001, Priya Sharma, priya.sharma@company...","EMP-1001, Priya Sharma, Operations"
1,1002,EMP,1002,EMP-1002,EMP-1002,priya kulkarni,PRIYA KULKARNI,Priya Kulkarni,14,Priya Kulkarni Operations,...,"Nagpur, Maharashtra",Operations,Salary: 35000,35000,35000,+91-7939042955,Mumbai-Pune-Mumbai,Mumbai-Pune-Pune,"EMP-1002, Priya Kulkarni, priya.kulkarni@gma...","EMP-1002, Priya Kulkarni, Operations"
2,1003,CON,1003,EMP-1003,CON-1003,amit sharma,AMIT SHARMA,Amit Sharma,11,Amit Sharma HR,...,Ahmednagar-Maharashtra,HR,Salary: 80000,80000,"80,000",+91-9340505846,Nagpur-Pune-Mumbai,Nagpur-Pune-Pune,"EMP-1003, Amit Sharma, amit.sharma@yahoo.com...","EMP-1003, Amit Sharma, HR"
3,1004,EMP,1004,EMP-1004,EMP-1004,vikas kulkarni,VIKAS KULKARNI,Vikas Kulkarni,14,Vikas Kulkarni HR,...,"nashik , Maharashtra",HR,Salary: 60000,60000,60000,+91-8461364854,Pune-Nashik-Mumbai,Pune-Nashik-Pune,"EMP-1004, Vikas Kulkarni, vikas.kulkarni@gma...","EMP-1004, Vikas Kulkarni, HR"
4,1005,STF,1005,EMP-1005,STF-1005,sneha patil,SNEHA PATIL,Sneha Patil,11,Sneha Patil Operations,...,PUNE-Maharashtra,Operations,Salary: 35000,35000,35000,+91-8541804686,Pune-Nashik-Mumbai,Pune-Nashik-Pune,"EMP-1005, Sneha Patil, sneha.patil@gmail.com...","EMP-1005, Sneha Patil, Operations"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,EMP,1096,EMP-1096,EMP-1096,amit joshi,AMIT JOSHI,Amit Joshi,10,Amit Joshi Operations,...,"mumbai , Maharashtra",Operations,Salary: 30000,30000,"30,000",+91-8754569613,Nagpur-Pune-Mumbai,Nagpur-Pune-Pune,"EMP-1096, Amit Joshi, amit.joshi@gmail.com, ...","EMP-1096, Amit Joshi, Operations"
96,1097,STF,1097,EMP-1097,STF-1097,vikas deshmukh,VIKAS DESHMUKH,Vikas Deshmukh,14,Vikas Deshmukh HR,...,Pune-Maharashtra,HR,Salary: 50000,50000,50000,+91-8950049698,Pune-Mumbai-Mumbai,Pune-Pune-Mumbai,"EMP-1097, Vikas Deshmukh, vikas.deshmukh@yah...","EMP-1097, Vikas Deshmukh, HR"
97,1098,STF,1098,EMP-1098,STF-1098,rohan kulkarni,ROHAN KULKARNI,Rohan Kulkarni,14,Rohan Kulkarni HR,...,"Aurangabad, Maharashtra",HR,Salary: 35000,35000,35000,+91-9338877621,Mumbai-Pune-Mumbai,Mumbai-Pune-Pune,"EMP-1098, Rohan Kulkarni, rohan.kulkarni @ya...","EMP-1098, Rohan Kulkarni, HR"
98,1099,EMP,1099,EMP-1099,EMP-1099,rohan kumar,ROHAN KUMAR,Rohan Kumar,11,Rohan Kumar IT,...,Pune-Maharashtra,IT,Salary: 50000,50000,"50,000",+91-9555694670,Pune-Nashik-Mumbai,Pune-Nashik-Pune,"EMP-1099, Rohan Kumar, rohan.kumar@gmail.com...","EMP-1099, Rohan Kumar, IT"


In [17]:
df.head
df.isnull
df.shape
df.sum


<bound method DataFrame.sum of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001   
1                 1002             EMP             1002    EMP-1002   
2                 1003             CON             1003    EMP-1003   
3                 1004             EMP             1004    EMP-1004   
4                 1005             STF             1005    EMP-1005   
..                 ...             ...              ...         ...   
95                1096             EMP             1096    EMP-1096   
96                1097             STF             1097    EMP-1097   
97                1098             STF             1098    EMP-1098   
98                1099             EMP             1099    EMP-1099   
99                1100             CON             1100    EMP-1100   

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHAR

In [18]:
df.isna

<bound method DataFrame.isna of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001   
1                 1002             EMP             1002    EMP-1002   
2                 1003             CON             1003    EMP-1003   
3                 1004             EMP             1004    EMP-1004   
4                 1005             STF             1005    EMP-1005   
..                 ...             ...              ...         ...   
95                1096             EMP             1096    EMP-1096   
96                1097             STF             1097    EMP-1097   
97                1098             STF             1098    EMP-1098   
98                1099             EMP             1099    EMP-1099   
99                1100             CON             1100    EMP-1100   

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHA

In [19]:
df.shape

(100, 44)

In [20]:
df.isna

<bound method DataFrame.isna of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001   
1                 1002             EMP             1002    EMP-1002   
2                 1003             CON             1003    EMP-1003   
3                 1004             EMP             1004    EMP-1004   
4                 1005             STF             1005    EMP-1005   
..                 ...             ...              ...         ...   
95                1096             EMP             1096    EMP-1096   
96                1097             STF             1097    EMP-1097   
97                1098             STF             1098    EMP-1098   
98                1099             EMP             1099    EMP-1099   
99                1100             CON             1100    EMP-1100   

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHA

In [21]:
df.sum

<bound method DataFrame.sum of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001   
1                 1002             EMP             1002    EMP-1002   
2                 1003             CON             1003    EMP-1003   
3                 1004             EMP             1004    EMP-1004   
4                 1005             STF             1005    EMP-1005   
..                 ...             ...              ...         ...   
95                1096             EMP             1096    EMP-1096   
96                1097             STF             1097    EMP-1097   
97                1098             STF             1098    EMP-1098   
98                1099             EMP             1099    EMP-1099   
99                1100             CON             1100    EMP-1100   

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHAR

In [22]:
df.isna

<bound method DataFrame.isna of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001   
1                 1002             EMP             1002    EMP-1002   
2                 1003             CON             1003    EMP-1003   
3                 1004             EMP             1004    EMP-1004   
4                 1005             STF             1005    EMP-1005   
..                 ...             ...              ...         ...   
95                1096             EMP             1096    EMP-1096   
96                1097             STF             1097    EMP-1097   
97                1098             STF             1098    EMP-1098   
98                1099             EMP             1099    EMP-1099   
99                1100             CON             1100    EMP-1100   

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHA